name: Docker Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Set git proxy
      run: |
        git config --global http.proxy socks5h://127.0.0.1:1080
        git config --global https.proxy socks5h://127.0.0.1:1080

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Docker image
      run: make build

    - name: Run container
      run: make run

    - name: Test nginx service
      run: |
        sleep 5
        make test
